development:
  S3_BUCKET_NAME: mydanebook
  AWS_ACCESS_KEY_ID: AKIAI6Q32IMKPK36Q5WQ
  AWS_SECRET_ACCESS_KEY: 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

production:
  S3_BUCKET_NAME: mydanebook
  AWS_ACCESS_KEY_ID: AKIAI6Q32IMKPK36Q5WQ
  AWS_SECRET_ACCESS_KEY: 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